//
// Created by Artem on 08.04.2024.
//

#ifndef TUSA_ANDROID_RENDER_TILES_ENUM_H
#define TUSA_ANDROID_RENDER_TILES_ENUM_H


enum RenderTilesEnum {
    SHOW_LEFT,
    SHOW_RIGHT,
    SHOW_TOP,
    SHOW_BOTTOM,
    ONLY_MIDDLE
};


#endif //TUSA_ANDROID_RENDER_TILES_ENUM_H
