/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artem.tusaandroid.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param phone 
 * @param avatar 
 * @param creation 
 * @param id 
 */


data class AvatarEntity (

    @Json(name = "phone")
    val phone: kotlin.String,

    @Json(name = "avatar")
    val avatar: kotlin.ByteArray,

    @Json(name = "creation")
    val creation: java.time.OffsetDateTime,

    @Json(name = "id")
    val id: kotlin.Long? = null

) {


}

