/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artem.tusaandroid.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param fromPhone 
 * @param toPhone 
 * @param date 
 * @param activated 
 * @param id 
 */


data class FriendRequestEntity (

    @Json(name = "fromPhone")
    val fromPhone: kotlin.String,

    @Json(name = "toPhone")
    val toPhone: kotlin.String,

    @Json(name = "date")
    val date: java.time.OffsetDateTime,

    @Json(name = "activated")
    val activated: kotlin.Boolean,

    @Json(name = "id")
    val id: kotlin.Long? = null

) {


}

