/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artem.tusaandroid.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param owner 
 * @param hasFriend 
 * @param id 
 */


data class FriendEntity (

    @Json(name = "owner")
    val owner: kotlin.String,

    @Json(name = "hasFriend")
    val hasFriend: kotlin.String,

    @Json(name = "id")
    val id: kotlin.Long? = null

) {


}

