/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artem.tusaandroid.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param encoded 
 * @param format 
 * @param algorithm 
 * @param destroyed 
 */


data class GenerateSecretKey200Response (

    @Json(name = "encoded")
    val encoded: kotlin.ByteArray? = null,

    @Json(name = "format")
    val format: kotlin.String? = null,

    @Json(name = "algorithm")
    val algorithm: kotlin.String? = null,

    @Json(name = "destroyed")
    val destroyed: kotlin.Boolean? = null

) {


}

