/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.artem.tusaandroid.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param uniqueName 
 * @param name 
 * @param jwt 
 */


data class LoginResponseDto (

    @Json(name = "uniqueName")
    val uniqueName: kotlin.String,

    @Json(name = "name")
    val name: kotlin.String,

    @Json(name = "jwt")
    val jwt: kotlin.String

) {


}

