name: Move APK File

on:
  push:
    branches:
      - main  # Trigger workflow on pushes to the main branch
  workflow_dispatch: # Allow manual trigger of the workflow

jobs:
  move-apk:
    runs-on: self-hosted
    steps:
      - name: Set up custom git config
        run: git config --global http.postBuffer 1048576000

      # Check out the repository code
      - uses: actions/checkout@v4

      - name: Move APK File
        run: |
          cp app/release/app-release.apk /opt/tucik/tucik.apk
          cp app/privacy.pdf /opt/tucik/privacy.pdf
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}